// <auto-generated />
using System;
using Logistica.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Logistica.API.Migrations
{
    [DbContext(typeof(LogisticaDbContext))]
    [Migration("20260616063847_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.28")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Logistica.API.Models.Envio", b =>
                {
                    b.Property<int>("IdEnvio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_envio");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdEnvio"));

                    b.Property<DateTime>("FechaEnvio")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_envio");

                    b.Property<int>("IdRepartidor")
                        .HasColumnType("integer")
                        .HasColumnName("id_repartidor");

                    b.Property<int>("IdZona")
                        .HasColumnType("integer")
                        .HasColumnName("id_zona");

                    b.Property<decimal>("PesoKg")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("peso_kg");

                    b.HasKey("IdEnvio");

                    b.HasIndex("IdRepartidor");

                    b.HasIndex("IdZona");

                    b.ToTable("envios");

                    b.HasData(
                        new
                        {
                            IdEnvio = 1,
                            FechaEnvio = new DateTime(2025, 5, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            IdRepartidor = 1,
                            IdZona = 1,
                            PesoKg = 10.00m
                        },
                        new
                        {
                            IdEnvio = 2,
                            FechaEnvio = new DateTime(2025, 5, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            IdRepartidor = 1,
                            IdZona = 1,
                            PesoKg = 12.00m
                        },
                        new
                        {
                            IdEnvio = 3,
                            FechaEnvio = new DateTime(2025, 5, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            IdRepartidor = 1,
                            IdZona = 1,
                            PesoKg = 10.00m
                        },
                        new
                        {
                            IdEnvio = 4,
                            FechaEnvio = new DateTime(2025, 5, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            IdRepartidor = 2,
                            IdZona = 2,
                            PesoKg = 8.00m
                        },
                        new
                        {
                            IdEnvio = 5,
                            FechaEnvio = new DateTime(2025, 5, 18, 0, 0, 0, 0, DateTimeKind.Utc),
                            IdRepartidor = 2,
                            IdZona = 2,
                            PesoKg = 10.00m
                        },
                        new
                        {
                            IdEnvio = 6,
                            FechaEnvio = new DateTime(2025, 5, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            IdRepartidor = 1,
                            IdZona = 3,
                            PesoKg = 5.50m
                        },
                        new
                        {
                            IdEnvio = 7,
                            FechaEnvio = new DateTime(2025, 5, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            IdRepartidor = 2,
                            IdZona = 1,
                            PesoKg = 7.00m
                        },
                        new
                        {
                            IdEnvio = 8,
                            FechaEnvio = new DateTime(2025, 4, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            IdRepartidor = 3,
                            IdZona = 1,
                            PesoKg = 15.00m
                        },
                        new
                        {
                            IdEnvio = 9,
                            FechaEnvio = new DateTime(2025, 6, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            IdRepartidor = 1,
                            IdZona = 2,
                            PesoKg = 6.00m
                        },
                        new
                        {
                            IdEnvio = 10,
                            FechaEnvio = new DateTime(2025, 6, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            IdRepartidor = 3,
                            IdZona = 3,
                            PesoKg = 9.00m
                        });
                });

            modelBuilder.Entity("Logistica.API.Models.Repartidor", b =>
                {
                    b.Property<int>("IdRepartidor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_repartidor");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdRepartidor"));

                    b.Property<string>("Email")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("email");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombre");

                    b.HasKey("IdRepartidor");

                    b.ToTable("repartidores");

                    b.HasData(
                        new
                        {
                            IdRepartidor = 1,
                            Email = "andres@logistica.com",
                            Nombre = "Andrés"
                        },
                        new
                        {
                            IdRepartidor = 2,
                            Email = "camila@logistica.com",
                            Nombre = "Camila"
                        },
                        new
                        {
                            IdRepartidor = 3,
                            Email = "luis@logistica.com",
                            Nombre = "Luis"
                        });
                });

            modelBuilder.Entity("Logistica.API.Models.Zona", b =>
                {
                    b.Property<int>("IdZona")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_zona");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdZona"));

                    b.Property<string>("NombreZona")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombre_zona");

                    b.Property<decimal>("TarifaPorKg")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("tarifa_por_kg");

                    b.HasKey("IdZona");

                    b.ToTable("zonas");

                    b.HasData(
                        new
                        {
                            IdZona = 1,
                            NombreZona = "Norte",
                            TarifaPorKg = 1.50m
                        },
                        new
                        {
                            IdZona = 2,
                            NombreZona = "Sur",
                            TarifaPorKg = 2.00m
                        },
                        new
                        {
                            IdZona = 3,
                            NombreZona = "Centro",
                            TarifaPorKg = 1.75m
                        });
                });

            modelBuilder.Entity("Logistica.API.Models.Envio", b =>
                {
                    b.HasOne("Logistica.API.Models.Repartidor", "Repartidor")
                        .WithMany("Envios")
                        .HasForeignKey("IdRepartidor")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Logistica.API.Models.Zona", "Zona")
                        .WithMany("Envios")
                        .HasForeignKey("IdZona")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Repartidor");

                    b.Navigation("Zona");
                });

            modelBuilder.Entity("Logistica.API.Models.Repartidor", b =>
                {
                    b.Navigation("Envios");
                });

            modelBuilder.Entity("Logistica.API.Models.Zona", b =>
                {
                    b.Navigation("Envios");
                });
#pragma warning restore 612, 618
        }
    }
}
